services:
  backend:
    container_name: turbo_backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  spa:
    container_name: turbo_spa
    build:
      context: .
      dockerfile: ./apps/spa/Dockerfile
    restart: always
    ports:
      - 3001:80
    networks:
      - app_network

networks:
  app_network:
